name: laf-test
appid: gvfh2x
invokeUrl: https://gvfh2x.laf.run
function:
  developToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBpZCI6Imd2ZmgyeCIsInR5cGUiOiJkZXZlbG9wIiwiZXhwIjoxNjg5ODIyODMyLCJpYXQiOjE2ODkyMTgwMzJ9.94ZIOgf0P5TI-XC5Rbk49EVDyOXHGAJ3oLKlD_UE9ko
  developTokenExpire: 1689822832
storage:
  endpoint: https://oss.laf.run
  accessKeyId: WQYI3I4VJ72OLNQV7ZI2
  accessKeySecret: KWzdHg7G68dJiVeBfpNAHf2NmWzQ1UIaumDs1+bo
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJXUVlJM0k0Vko3Mk9MTlFWN1pJMiIsImV4cCI6MTY4OTgyMjgzMiwicGFyZW50IjoiZ3ZmaDJ4Iiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.ySKuk3hNDGYpG-qcJdICq8vSTA6dux1xJfAZhK2BNvBBu25wq67mABCaYZv__8WFRVs9ycc8t69ErN4-I786YA
  expire: 1689822832
